name: Build Full OpenHardwareMonitor App

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet Packages
      run: nuget restore OpenHardwareMonitor.sln

    - name: Build Full Solution
      run: msbuild OpenHardwareMonitor.sln /p:Configuration=Release /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.5

    - name: Upload Binaries Artifact
      uses: actions/upload-artifact@v4
      with:
        name: OpenHardwareMonitor-App
        path: |
          **/bin/Release/
          **/Bin/Release/
